### PR TITLE
Bump

### PR DESCRIPTION
**Pull request by Jaykul**
I'm not really making a change, sorry. Just trying to trigger the build for the [1911.20](https://github.com/microsoft/cascadia-code/releases/tag/v1911.20) release.

### CODE REVIEW

**Comment by Jaykul** [comment]
Well. That was dissapointing 🤔 I guess it failed because _they_ added the PowerLine characters and caused a conflict or something. 😟

**Comment by Finii** [comment]
They seemed to have added ``regular`` to the description which is used by the font patcher to name the font. Afterwards we can't find the patched font anymore, because we hardcoded the resulting filename, which is autogenerated by font-patcher.
Probably I find time to have a closer look tomorrow.

**Comment by Jaykul** [comment]
It's true, they have "Regular" and "Mono" now, with PowerLine variants of each.

**Comment by Finii** [comment]
Implemented a more prominent display of glyph clashes:

Screenshot from 2019-11-22 08-12-06

Microsoft having a PL variant is very good news of course, thank you.
I did not check which glyphs they added. For the 'Delugia complete' variant, that many things they will never add, so probably this repository still has it's uses.

Unfortunately I'm a bit tight on play time atm. Maybe next week.

Find the newest patched fonts in the other PR.

**Comment by adam7** [comment]
@Finii fixes this in #23 and we have a new release so closing

**Pull request closed without merging**
