### PR TITLE
Just to trigger new build

### PR DESCRIPTION
**Pull request by chunliu**
Please ignore this change...

### CODE REVIEW

**Comment by chunliu** [comment]
errr...

**Comment by Finii** [comment]
Not sure what happened here, there seems to be a change in fontforge itself.
I can not even use it manually right now, but that might be a lack of coffee...

**Comment by Finii** [comment]
Definitively a lack of coffee.
But I found the reason, will fix it in the afternoon.

**Comment by Finii** [comment]
Let's continue any discussion in #34.

**Pull request closed without merging**
